
import { Product } from './product';

export const PRODUCT: Product[] =[
  {
    id : 1,
    name: "Item 1",
    image: "http://placehold.it/700x400",
    price: 20000,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur",
    status: true,
  },
  {
    id: 2,
    name: "Item 2",
    image: "http://placehold.it/700x400",
    price: 50000,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur",
    status: true,
  },
  {
    id: 3,
    name: "Item 3",
    image: "http://placehold.it/700x400",
    price: 30000,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur",
    status: true,
  },
  {
    id: 4,
    name: "Item 4",
    image: "http://placehold.it/700x400",
    price: 40000,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur",
    status: true,
  },
  {
    id: 5,
    name: "Item 5",
    image: "http://placehold.it/700x400",
    price: 50000,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur",
    status: true,
  },
  {
    id: 6,
    name: "Item 6",
    image: "http://placehold.it/700x400",
    price: 30000,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur",
    status: true,
  },
  {
    id: 7,
    name: "Item 7",
    image: "http://placehold.it/700x400",
    price: 30000,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur",
    status: true,
  },
  {
    id: 8,
    name: "Item 8",
    image: "http://placehold.it/700x400",
    price: 30000,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur",
    status: true,
  },
  {
    id: 9,
    name: "Item 9",
    image: "http://placehold.it/700x400",
    price: 30000,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur",
    status: true,
  },
  {
    id: 10,
    name: "Item 10",
    image: "http://placehold.it/700x400",
    price: 30000,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur",
    status: true,
  }
]
